---
# Upload ISO image to HyperCore.
- name: Upload ISO image from http link to HyperCore
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    iso_url: https://releases.ubuntu.com/focal/ubuntu-20.04.5-live-server-amd64.iso
    iso_filename: "{{ iso_url | split('/') | last }}"

  tasks:
    - name: Get info about specific ISO image - {{ iso_filename }}
      scale_computing.hypercore.iso_info:
        name: "{{ iso_filename }}"
      register: iso_results

    - name: Stop if ISO already present
      meta: end_play
      when: iso_results.records != []

    # ------------------------------------------------------
    - name: Download ISO {{ iso_filename }} from URL
      ansible.builtin.get_url:
        url: "{{ iso_url }}"
        dest: /tmp/{{ iso_filename }}

    - name: Upload ISO {{ iso_filename }} to HyperCore
      scale_computing.hypercore.iso:
        name: "{{ iso_filename }}"
        source: /tmp/{{ iso_filename }}
        state: present

    - name: Get info about specific ISO image - {{ iso_filename }}
      scale_computing.hypercore.iso_info:
        name: "{{ iso_filename }}"
      register: iso_results

    - name: Show info about {{ iso_filename }} ISO
      debug:
        var: iso_results.records[0]
