collections:
  - name: community.general
    version: 6.3.0
  - name: scale_computing.hypercore
    version: 1.1.0
roles:
  - name: geerlingguy.docker
    version: 6.1.0
  - name: monolithprojects.github_actions_runner
    version: 1.17.0
#  macunha1.github_actions_runner
