name: CI-tests
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:
    inputs:
      run_slow_tests:
        description: 'Run slow integration tests?'
        type: boolean
        required: false
        default: false
jobs:
  integ:
    name: integ test
    runs-on: [ubuntu-latest]
    container: python:3.10-slim-buster
    steps:
      - run: echo inputs.run_slow_tests=${{ inputs.run_slow_tests }}
      - run: date
      - shell: bash
        run: |
          delay=20
          if [[ "${{ matrix.hc3_name }}" == "srv20" ]]
          then
            delay=$(( $delay + 20 ))
          fi
          if [[ "${{ matrix.test_name }}" == "bb" ]]
          then
            delay=$(( $delay + 20 ))
            fi
          sleep $delay
      - run: date
    strategy:
      fail-fast: false
      matrix:
        hc3_name: [srv10, srv20]
        test_name: [aa, bb]
    concurrency:
      group: integ-${{ matrix.hc3_name }}-${{ matrix.test_name }}
      cancel-in-progress: false
