name: CI-tests
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:
    inputs:
      run_slow_tests:
        description: 'Run slow integration tests?'
        type: boolean
        required: false
        default: false
jobs:
  mypy:
    name: Type checks (mypy)
    runs-on: [ubuntu-latest]
    container: python:3.10-slim-buster
    steps:
      - run: echo inputs.run_slow_tests=${{ inputs.run_slow_tests }}
      - run: date
      - run: sleep 60
      - run: date
    concurrency:
      group: srv10-mypy
      cancel-in-progress: false
